#
# TODO Configure Keycloak admin client (for adding users)
#
quarkus.keycloak.admin-client.server-url=http://keycloak:8180
quarkus.keycloak.admin-client.realm=master
quarkus.keycloak.admin-client.client-id=admin-cli
quarkus.keycloak.admin-client.username=admin
quarkus.keycloak.admin-client.password=admin
quarkus.keycloak.admin-client.grant-type=PASSWORD

#
# TODO Config properties
#
caf.client.realm=caf
caf.client.client-id=caf-webapp
caf.client.user-role=user

#
# TODO Endpoint URL for the images microservice
#
quarkus.rest-client.caf-images-api.url=http://caf-rest:5050

#
# TODO Configure token exchange for propagation to microservice
#
quarkus.oidc-token-propagation.enabled=true

quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.oidc".level=TRACE