#
# These are the same as the defaults.
#
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
%dev.quarkus.http.port=4040
#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=cs594
quarkus.container-image.name=caf-thumbnail
#
# Logging
#
quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.oidc".level=TRACE
#
# TODO JWT configuration for server
mp.jwt.verify.publickey.location=/publicKey.pem
mp.jwt.verify.issuer=https://caf-rest
mp.jwt.verify.audiences=caf-thumbnail
#
# TODO Amazon S3 (see caf-webapp)
quarkus.s3.aws.region=us-east-1
quarkus.s3.endpoint-override=http://localstack:4566
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=test
quarkus.s3.aws.credentials.static-provider.secret-access-key=test

