#
# These are the same as the defaults.
#
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=cs594
quarkus.container-image.name=caf-webapp
#
# Logging
#
quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.oidc".level=TRACE
#
# Config properties
#
caf.image.bucket=caf-images
caf.image.type=image/jpeg
caf.image.ext=jpg
caf.image.url=http://localhost:4566/%s/%s
caf.image.region=us-east-1
#
# TODO OIDC properties
quarkus.oidc.auth-server-url=http://keycloak:8180/realms/caf
quarkus.oidc.client-id=caf-webapp
quarkus.oidc.application-type=web-app
quarkus.oidc.credentials.secret=secret
#
# TODO Amazon S3
# https://docs.quarkiverse.io/quarkus-amazon-services/dev/amazon-s3.html
quarkus.s3.aws.region=us-east-1
quarkus.s3.endpoint-override=http://localstack:4566
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=test
quarkus.s3.aws.credentials.static-provider.secret-access-key=test
